version: '2'
services:
  oauth-primary:
    image: upmcenterprises/wso2-is:5.3.0.4
    ports:
      - "9446:9446"
    env_file:
      - .env
    environment:
      - USER=${WSO2_MYSQL_USER}
      - PASSWORD=${WSO2_MYSQL_PASSWORD}
      - PUBLICURL=localhost
      - SERVER=oauthdb-primary
      - DATABASENAME=${WSO2_MYSQL_DB}
      - HTTPSPORT=9446
      - PORT=${LOCAL_MYSQL_PORT_PRIMARY}    
    links:
      - "oauthdb-primary"
    volumes:
      - ./wso2/migrations:/opt/tmp
  oauthdb-primary:
    image: mysql:5.7
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${WSO2_MYSQL_DB}
      - MYSQL_USER=${WSO2_MYSQL_USER}
      - MYSQL_PASSWORD=${WSO2_MYSQL_PASSWORD}
    volumes:
      - primary-mysql-data:/var/lib/mysql    
    ports:
      - "${LOCAL_MYSQL_PORT_PRIMARY}:3306"
  oauth-secondary:
    image: upmcenterprises/wso2-is:5.3.0.4
    ports:
      - "9443:9443"
    env_file:
      - .env
    environment:
      - USER=${WSO2_MYSQL_USER}
      - PASSWORD=${WSO2_MYSQL_PASSWORD}
      - PUBLICURL=localhost
      - SERVER=oauthdb-secondary
      - DATABASENAME=${WSO2_MYSQL_DB}
      - HTTPSPORT=9443
      - PORT=${LOCAL_MYSQL_PORT_SECONDARY}
    links:
      - "oauthdb-secondary"
    volumes:
      - ./wso2/migrations:/opt/tmp
  oauthdb-secondary:
    image: mysql:5.7
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${WSO2_MYSQL_DB}
      - MYSQL_USER=${WSO2_MYSQL_USER}
      - MYSQL_PASSWORD=${WSO2_MYSQL_PASSWORD}
    volumes:
      - secondary-mysql-data:/var/lib/mysql
    ports:
      - "${LOCAL_MYSQL_PORT_SECONDARY}:3306"    
volumes:
  primary-mysql-data:
  secondary-mysql-data:
