version: '2'
services:
  nodeauth-client:
    build: nodeauth/.
    ports:
      - "${WSO2_NODE_CLIENT_PORT}:${WSO2_NODE_CLIENT_PORT}"
    env_file:
      - .env  
    links:
      - "oauthdb-primary"
    volumes:
      - ./.env:/usr/nodeAuth/.env    
  oauth-primary:
    image: upmcenterprises/wso2-is:5.3.0.4
    ports:
      - "9446:9446"
    env_file:
      - .env
    environment:
      - USER=${WSO2_MYSQL_USER}
      - PASSWORD=${WSO2_MYSQL_PASSWORD}
      - PUBLICURL=localhost
      - SERVER=oauthdb-primary
      - DATABASENAME=${WSO2_MYSQL_DB}
      - HTTPSPORT=9446
      - PORT=${LOCAL_MYSQL_PORT_PRIMARY}    
    links:
      - "oauthdb-primary"
    volumes:
      - ./wso2/migrations/v1-init.sql:/opt/tmp/v1-init.sql
      - ./wso2/migrations/v2-insert-jwt-claims.sql:/opt/tmp/v2-insert-jwt-claims.sql
      - ./wso2/migrations/v3-insert-seed-users.sql:/opt/tmp/v3-insert-seed-users.sql
      - ./wso2/migrations/v4-insert-seed-service-providers.sql:/opt/tmp/v4-insert-seed-service-providers.sql
      - ./wso2/migrations/v5-primary-insert-seed-users.sql:/opt/tmp/v5-primary-insert-seed-users.sql
      - ./wso2/migrations/v6-primary-seed-fed-service-provider.sql:/opt/tmp/v6-primary-seed-fed-service-provider.sql
      - ./wso2/migrations/v7-primary-seed-fed-id-providers.sql:/opt/tmp/v7-primary-seed-fed-id-providers.sql
  oauthdb-primary:
    image: mysql:5.7
    ports:
      - "${LOCAL_MYSQL_PORT_PRIMARY}:3306"
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${WSO2_MYSQL_DB}
      - MYSQL_USER=${WSO2_MYSQL_USER}
      - MYSQL_PASSWORD=${WSO2_MYSQL_PASSWORD}
    volumes:
      - primary-mysql-data:/var/lib/mysql
  oauth-secondary:
    image: upmcenterprises/wso2-is:5.3.0.4
    ports:
      - "9443:9443"
    env_file:
      - .env
    environment:
      - USER=${WSO2_MYSQL_USER}
      - PASSWORD=${WSO2_MYSQL_PASSWORD}
      - PUBLICURL=localhost
      - SERVER=oauthdb-secondary
      - DATABASENAME=${WSO2_MYSQL_DB}
      - HTTPSPORT=9443
      - PORT=${LOCAL_MYSQL_PORT_SECONDARY}
    links:
      - "oauthdb-secondary"
    volumes:
      - ./wso2/migrations/v1-init.sql:/opt/tmp/v1-init.sql
      - ./wso2/migrations/v2-insert-jwt-claims.sql:/opt/tmp/v2-insert-jwt-claims.sql
      - ./wso2/migrations/v3-insert-seed-users.sql:/opt/tmp/v3-insert-seed-users.sql
      - ./wso2/migrations/v4-insert-seed-service-providers.sql:/opt/tmp/v4-insert-seed-service-providers.sql
      - ./wso2/migrations/v5-secondary-insert-seed-users.sql:/opt/tmp/v5-secondary-insert-seed-users.sql
      - ./wso2/migrations/v6-secondary-seed-primary-fed-service-provider.sql:/opt/tmp/v6-secondary-seed-primary-fed-service-provider.sql
  oauthdb-secondary:
    image: mysql:5.7
    ports:
      - "${LOCAL_MYSQL_PORT_SECONDARY}:3306" 
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${WSO2_MYSQL_DB}
      - MYSQL_USER=${WSO2_MYSQL_USER}
      - MYSQL_PASSWORD=${WSO2_MYSQL_PASSWORD}
    volumes:
      - secondary-mysql-data:/var/lib/mysql       
volumes:
  primary-mysql-data:
  secondary-mysql-data:
