
LOCK TABLES `UM_HYBRID_ROLE` WRITE;
/*!40000 ALTER TABLE `UM_HYBRID_ROLE` DISABLE KEYS */;
INSERT INTO `UM_HYBRID_ROLE` (UM_ID, UM_ROLE_NAME, UM_TENANT_ID) VALUES (2,'Application/3pl-api-test',-1234);
/*!40000 ALTER TABLE `UM_HYBRID_ROLE` ENABLE KEYS */;
ALTER TABLE `UM_HYBRID_ROLE` AUTO_INCREMENT = 3;
UNLOCK TABLES;

LOCK TABLES `UM_HYBRID_USER_ROLE` WRITE;
/*!40000 ALTER TABLE `UM_HYBRID_USER_ROLE` DISABLE KEYS */;
INSERT INTO `UM_HYBRID_USER_ROLE` (UM_ID, UM_USER_NAME, UM_ROLE_ID, UM_TENANT_ID, UM_DOMAIN_ID) VALUES (1,'admin',2,-1234,1), (2,'3pl-test-user',2,-1234,1);
/*!40000 ALTER TABLE `UM_HYBRID_USER_ROLE` ENABLE KEYS */;
ALTER TABLE `UM_HYBRID_USER_ROLE` AUTO_INCREMENT = 3;
UNLOCK TABLES;

LOCK TABLES `UM_ROLE` WRITE;
/*!40000 ALTER TABLE `UM_ROLE` DISABLE KEYS */;
INSERT INTO `UM_ROLE` (UM_ID, UM_ROLE_NAME, UM_TENANT_ID, UM_SHARED_ROLE) VALUES (2,'3pl-test-role',-1234,0);
/*!40000 ALTER TABLE `UM_ROLE` ENABLE KEYS */;
ALTER TABLE `UM_ROLE` AUTO_INCREMENT = 3;
UNLOCK TABLES;


LOCK TABLES `UM_USER` WRITE;
/*Relying default date for UM_CHANGED_TIME respectively*/
/*!40000 ALTER TABLE `UM_USER` DISABLE KEYS */;
INSERT INTO `UM_USER` (UM_ID, UM_USER_NAME, UM_USER_PASSWORD, UM_SALT_VALUE, UM_REQUIRE_CHANGE, UM_TENANT_ID) VALUES (2, '3pl-test-user','ODP7J0VIf8T3dXoydVBdrjswpi8c6fGeRqYQ5s7AVBM=','Ajwqep5fMvKmLYphgs/03w==',0,-1234);
/*!40000 ALTER TABLE `UM_USER` ENABLE KEYS */;
ALTER TABLE `UM_USER` AUTO_INCREMENT = 3;
UNLOCK TABLES;

LOCK TABLES `UM_USER_ROLE` WRITE;
/*!40000 ALTER TABLE `UM_USER_ROLE` DISABLE KEYS */;
INSERT INTO `UM_USER_ROLE` (UM_ROLE_ID, UM_USER_ID, UM_TENANT_ID) VALUES (2,2,-1234);
/*!40000 ALTER TABLE `UM_USER_ROLE` ENABLE KEYS */;
UNLOCK TABLES;