apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dev.web.wso2.upmce
  annotations:
    emmie-update: dev.web.wso2.upmce
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        imagePullPolicy: Always
        image: gcr.io/sso-wso2-intro-3-tier/sso/wso2/web:1.0
        ports:
          - name: html
            containerPort: 8080		