oauth-primary:
  image: upmcenterprises/wso2-is:5.3.0.4
  ports:
    - "9443:9443"
  environment:
    - USER=regadmin
    - PASSWORD=regadmin
    - PUBLICURL=localhost
    - SERVER=oauthdb
    - DATABASENAME=regdb
    - HTTPSPORT=9443    
  links:
    - "oauthdb"
  volumes:
    - ./migrations:/opt/tmp
oauthdb:
  image: mysql:5.7
  environment:
    - MYSQL_ROOT_PASSWORD=wso21234
    - MYSQL_DATABASE=regdb
    - MYSQL_USER=regadmin
    - MYSQL_PASSWORD=regadmin   
  ports:
    - "3306:3306"