oauth:
  image: dickm/issue10/fix:1.0
  restart: always
  ports:
    - "9445:9443"
  environment:
    - USER=regadmin
    - PASSWORD=regadmin
    - PUBLICURL=localhost
    - SERVER=oauthdb
    - DATABASENAME=regdbTwo
  links:
    - "oauthdb"
  volumes:
    - ./certs:/opt/wso2/repository/resources/security
    - ./migrations:/opt/flyway/sql
oauthdb:
  image: mysql:5.7
  environment:
    - MYSQL_ROOT_PASSWORD=wso21234
    - MYSQL_DATABASE=regdbTwo
    - MYSQL_USER=regadmin
    - MYSQL_PASSWORD=regadmin
  ports:
    - "3306:3306"