oauth:
  image: upmcenterprises/wso2-is:5.3.0.4
  restart: always
  ports:
    - "9443:9443"
  environment:
    - USER=regadmin
    - PASSWORD=regadmin
    - PUBLICURL=localhost
    - SERVER=oauthdb
    - DATABASENAME=regdb
    - HTTPSPORT=9443
  links:
    - "oauthdb"
  volumes:
    - ./certs/wso2carbon-control.jks:/opt/wso2/repository/resources/security/wso2carbon.jks
    - ./certs/client-truststore.jks:/opt/wso2/repository/resources/security/client-truststore.jks
    - ./migrations:/opt/tmp
oauthdb:
  image: mysql:5.7
  environment:
    - MYSQL_ROOT_PASSWORD=wso21234
    - MYSQL_DATABASE=regdb
    - MYSQL_USER=regadmin
    - MYSQL_PASSWORD=regadmin
  volumes:
    - ./db/second:/var/lib/mysql
  ports:
    - "3306:3306"