oauth-primary:
  image: upmcenterprises/wso2-is:5.3.0.4
  ports:
    - "9446:9446"
  environment:
    - USER=regadmin
    - PASSWORD=regadmin
    - PUBLICURL=localhost
    - SERVER=oauthdb-primary
    - DATABASENAME=regdb
    - HTTPSPORT=9446
    - PORT=3307    
  links:
    - "oauthdb-primary"
  volumes:
    - ./certs/wso2-new.jks:/opt/wso2/repository/resources/security/wso2carbon.jks
    - ./certs/client-truststore.jks:/opt/wso2/repository/resources/security/client-truststore.jks
    - ./migrations:/opt/tmp
oauthdb-primary:
  image: mysql:5.7
  environment:
    - MYSQL_ROOT_PASSWORD=wso21234
    - MYSQL_DATABASE=regdb
    - MYSQL_USER=regadmin
    - MYSQL_PASSWORD=regadmin
  volumes:
    - ./db/first:/var/lib/mysql    
  ports:
    - "3307:3306"