/*STEP: add external claim for scope*/
/*ASSUME ID has AUTOINCREMENT*/
LOCK TABLES `IDN_CLAIM` WRITE;
/*!40000 ALTER TABLE `IDN_CLAIM` DISABLE KEYS */;
INSERT INTO IDN_CLAIM (DIALECT_ID, CLAIM_URI, TENANT_ID) VALUES  (4 /*oidc*/, 'scope', -1234);
/*!40000 ALTER TABLE `IDN_CLAIM` ENABLE KEYS */;
UNLOCK TABLES;

SET @scope_claim_id = LAST_INSERT_ID();

/*STEP: map new external claim scope to local claim role */
/*ASSUME ID has AUTOINCREMENT*/
LOCK TABLES `IDN_CLAIM_MAPPING` WRITE;
/*!40000 ALTER TABLE `IDN_CLAIM_MAPPING` DISABLE KEYS */;
INSERT INTO IDN_CLAIM_MAPPING (EXT_CLAIM_ID, MAPPED_LOCAL_CLAIM_ID, TENANT_ID) VALUES (@scope_claim_id,  34 /*role local claim*/, -1234);
/*!40000 ALTER TABLE `IDN_CLAIM_MAPPING` ENABLE KEYS */;
UNLOCK TABLES;


/*STEP: add dump of reg values in order to include local claims to openid registry so they appear when scope requested*/
/*ASSUME ID has AUTOINCREMENT*/
LOCK TABLES `REG_PROPERTY` WRITE;
/*!40000 ALTER TABLE `REG_PROPERTY` DISABLE KEYS */;
UPDATE REG_PROPERTY SET REG_VALUE = CONCAT('username,scope,',REG_VALUE) WHERE REG_TENANT_ID = -1234 AND REG_NAME = 'openid';
/*!40000 ALTER TABLE `REG_PROPERTY` ENABLE KEYS */;
ALTER TABLE `REG_PROPERTY` AUTO_INCREMENT = 2;
UNLOCK TABLES;