
LOCK TABLES `UM_HYBRID_ROLE` WRITE;
/*!40000 ALTER TABLE `UM_HYBRID_ROLE` DISABLE KEYS */;
INSERT INTO `UM_HYBRID_ROLE` (UM_ROLE_NAME, UM_TENANT_ID) VALUES ('Application/wso2-test-api-federated',-1234);
/*!40000 ALTER TABLE `UM_HYBRID_ROLE` ENABLE KEYS */;
UNLOCK TABLES;

SET @hybrid_role_id = LAST_INSERT_ID();

LOCK TABLES `UM_HYBRID_USER_ROLE` WRITE;
/*!40000 ALTER TABLE `UM_HYBRID_USER_ROLE` DISABLE KEYS */;
INSERT INTO `UM_HYBRID_USER_ROLE` (UM_USER_NAME, UM_ROLE_ID, UM_TENANT_ID, UM_DOMAIN_ID) VALUES ('admin',@hybrid_role_id,-1234,1), ('wso2-primary-test-user',@hybrid_role_id,-1234,1);
/*!40000 ALTER TABLE `UM_HYBRID_USER_ROLE` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `UM_USER` WRITE;
/*Relying default date for UM_CHANGED_TIME respectively*/
/*!40000 ALTER TABLE `UM_USER` DISABLE KEYS */;
INSERT INTO `UM_USER` (UM_USER_NAME, UM_USER_PASSWORD, UM_SALT_VALUE, UM_REQUIRE_CHANGE, UM_TENANT_ID) VALUES ('wso2-primary-test-user','ZcWQf8NQVAp0+uDQbtjugDFYVHUsltaT5AOuVk6ebUM=','dhO95O60fqoqxwKL3oQuGw==',0,-1234);
/*!40000 ALTER TABLE `UM_USER` ENABLE KEYS */;
UNLOCK TABLES;