
LOCK TABLES `UM_HYBRID_ROLE` WRITE;
/*!40000 ALTER TABLE `UM_HYBRID_ROLE` DISABLE KEYS */;
INSERT INTO `UM_HYBRID_ROLE` (UM_ROLE_NAME, UM_TENANT_ID) VALUES ('Application/Primary',-1234);
/*!40000 ALTER TABLE `UM_HYBRID_ROLE` ENABLE KEYS */;
UNLOCK TABLES;

SET @hybrid_role_id = LAST_INSERT_ID();

LOCK TABLES `UM_HYBRID_USER_ROLE` WRITE;
/*!40000 ALTER TABLE `UM_HYBRID_USER_ROLE` DISABLE KEYS */;
INSERT INTO `UM_HYBRID_USER_ROLE` (UM_USER_NAME, UM_ROLE_ID, UM_TENANT_ID, UM_DOMAIN_ID) VALUES ('admin',@hybrid_role_id,-1234,1), ('wso2-secondary-test-user',@hybrid_role_id,-1234,1);
/*!40000 ALTER TABLE `UM_HYBRID_USER_ROLE` ENABLE KEYS */;
UNLOCK TABLES;

LOCK TABLES `UM_USER` WRITE;
/*Relying default date for UM_CHANGED_TIME respectively*/
/*!40000 ALTER TABLE `UM_USER` DISABLE KEYS */;
INSERT INTO `UM_USER` (UM_USER_NAME, UM_USER_PASSWORD, UM_SALT_VALUE, UM_REQUIRE_CHANGE, UM_TENANT_ID) VALUES ('wso2-secondary-test-user','0sFJkR23Fi0KV/30jRawRV0Cg5yDRGp44uqyQ3vvuhA=','1a6CkKD89eiprq3lO3Qveg==',0,-1234);
/*!40000 ALTER TABLE `UM_USER` ENABLE KEYS */;
UNLOCK TABLES;